#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : PyMySQL
Version  : 0.7.11
Release  : 22
URL      : https://pypi.debian.net/PyMySQL/PyMySQL-0.7.11.tar.gz
Source0  : https://pypi.debian.net/PyMySQL/PyMySQL-0.7.11.tar.gz
Summary  : Pure Python MySQL Driver
Group    : Development/Tools
License  : MIT
Requires: PyMySQL-python
BuildRequires : mariadb-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://readthedocs.org/projects/pymysql/badge/?version=latest
:target: http://pymysql.readthedocs.io/en/latest/?badge=latest
:alt: Documentation Status

%package python
Summary: python components for the PyMySQL package.
Group: Default
Provides: pymysql-python

%description python
python components for the PyMySQL package.


%prep
%setup -q -n PyMySQL-0.7.11

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492395888
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492395888
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
